# Adapted from https://github.com/python-poetry/poetry/blob/master/.github/workflows/release.yml
name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: rstr-client

      - name: Checkout code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Poetry
        if: ${{ steps.release.outputs.release_created }}
        run: |
          pip install poetry
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Check Version
        if: ${{ steps.release.outputs.release_created }}
        id: check-version
        env:
          TAG_NAME: ${{ steps.release.outputs.tag_name }}
        run: |
          [[ v"$(poetry version --short)" = "$TAG_NAME" ]] \
            || (echo "version does not match tag" && exit 1)

      - name: Build project for distribution
        if: ${{ steps.release.outputs.release_created }}
        run: poetry build

      - name: Publish to PyPI
        if: ${{ steps.release.outputs.release_created }}
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish -u __token__ -p $POETRY_PYPI_TOKEN_PYPI
